### ISSUE TITLE
Tambahkan Blog Saya Juga Dong

### ISSUE THREAD

**Issue by mzaini30** [gohugoid/list-web-hugo-indonesia#8]
Blog saya: http://blog2.muhammadzaini.com

**Comment by ardianta** [comment]
Silahkan edit [README.md](https://github.com/gohugoid/list-web-hugo-indonesia/blob/master/README.md)

**Comment by mzaini30** [comment]
Ntar lah. Mati lampu masih
Pada tanggal 27 Sep 2018 18.42, "Ardianta" <notifications@github.com>
menulis:
